
name: pr

pr:
  autoCancel: false # Whether to cancel running PR builds when a new commit lands in the branch.
  branches: # Branch names to include or exclude for triggering a run.
    include:  # List of items to include.
    - main
  drafts: false

resources:
  repositories:
    - repository: pipelines
      type: git
      name: aztfmod_terraform-azurerm-caf-forked-laurentlesle/ci

jobs: 
- template: ci.yaml@pipelines
