
name: pr

pr:
  autoCancel: false # Whether to cancel running PR builds when a new commit lands in the branch. Default: true.
  branches: # Branch names to include or exclude for triggering a run.
    include:  # List of items to include.
    - main
  drafts: false


# pool:
#   name: contoso-level0

resources:
  containers:
  - container: rover
    image: aztfmod/rover:1.5.4-2307.2804

stages:
- stage: prep
  jobs:
  - job: analyse_changes
    steps:
    
    - checkout: git://aztfmod_terraform-azurerm-caf-forked-laurentlesle/pr_integration
      persistCredentials: true
      fetchTags: false
      clean: true
      
    - checkout: self
      fetchTags: true

    - bash: |
        ls -lsa
        cd pr_integration
        git config pull.rebase false 
        git checkout -b pr_examples/$(System.PullRequest.SourceCommitId) || git checkout pr_examples/$(System.PullRequest.SourceCommitId) && git pull
        git branch --set-upstream-to=origin/pr_examples/$(System.PullRequest.SourceCommitId) pr_examples/$(System.PullRequest.SourceCommitId)
        git remote -v
        
        cd ../terraform-azurerm-caf
        echo "git diff --name-only HEAD^"
        git diff --name-only HEAD^
        echo ""
        
        changed_folders=$(git diff --name-only HEAD^ | grep 'examples' | sort -u)
    
        if [ -z "$changed_folders" ]; then
          echo "Error: No paths with 'examples' found in the changed files."
          echo "Missing examples folder in the change set.\n"
          git diff --name-only HEAD^
          exit 2
        fi
    
        # Initialize an empty list to store the examples folders
        paths_without_filenames=()
    
        # Create a temporary YAML file with the generated matrix
        job_file="../pr_integration/jobs.yaml"
        echo "jobs:" > $job_file
          
        for folder in ${changed_folders[@]}; do
          echo "Processing: $folder"
          path_without_filename=$(dirname "$folder")
          echo "Adding: $path_without_filename"
          paths_without_filenames+=("$path_without_filename")
          formatted_string=$(echo "$path_without_filename" | sed 's/examples_//; s/[/\-]/_/g')
        
          echo "  - job: $formatted_string" >> $job_file
          echo "    steps:" >> $job_file
          echo "    - bash: echo 'Hello'" >> $job_file
        done
        
        pipeline_yaml_path="$job_file"
        echo "##vso[task.setvariable variable=pipeline_yaml_path;isOutput=true]$pipeline_yaml_path"        
        # Display the generated matrix YAML for verification
        cat $job_file
        
        # Join the array elements with a comma delimiter    
        CHANGED_FOLDERS=$(IFS=","; echo "${paths_without_filenames[*]}")
        echo "Content of CHANGED_FOLDERS"
        echo $CHANGED_FOLDERS
    
        echo "set output variable"
        echo "##vso[task.setvariable variable=EXAMPLE_FOLDERS;isOutput=true]$CHANGED_FOLDERS"

        cd ../pr_integration
        git remote -v
        git diff
        git add .
        git pull
        git -c user.name='aztfmod.test' -c user.email='aazdo_pr_check@aztfmod.null' commit -am "Integration jobs"
        git push origin pr_examples/$(System.PullRequest.SourceCommitId)
        
      displayName: Getting the example folders
      name: changeset

