
name: pr

pr:
  autoCancel: false # Whether to cancel running PR builds when a new commit lands in the branch. Default: true.
  branches: # Branch names to include or exclude for triggering a run.
    include:  # List of items to include.
    - main
  drafts: false


# pool:
#   name: contoso-level0

resources:
  containers:
  - container: rover
    image: aztfmod/rover:1.5.4-2307.2804

stages:
- stage: prep
  jobs:
  - job: analyse_changes
    steps:
    - checkout: self
      fetchTags: true
    
    - bash: |
        echo "git diff --name-only HEAD^"
        git diff --name-only HEAD^
        echo ""
        
        changed_folders=$(git diff --name-only HEAD^ | grep 'examples' | sort -u)
    
        if [ -z "$changed_folders" ]; then
          echo "Error: No paths with 'examples' found in the changed files."
          echo "Missing examples folder in the change set.\n"
          git diff --name-only HEAD^
          exit 1
        fi
    
        # Initialize an empty list to store the examples folders
        paths_without_filenames=()
        matrix=""
    
        # Create a temporary YAML file with the generated matrix
        echo "jobs:" > jobs.yml
          
        for folder in ${changed_folders[@]}; do
          echo "Processing: $folder"
          path_without_filename=$(dirname "$folder")
          echo "Adding: $path_without_filename"
          paths_without_filenames+=("$path_without_filename")
          formatted_string=$(echo "$path_without_filename" | sed 's/examples_//; s/[/\-]/_/g')
        
          echo "  - job: $formatted_string" >> matrix.yml
          echo "    steps:" >> jobs.yml
          echo "    - bash: echo 'Hello'" >> matrix.yml
        done
        
        pipeline_yaml_path="jobs.yml"
        echo "##vso[task.setvariable variable=pipeline_yaml_path;isOutput=true]$pipeline_yaml_path"        
        # Display the generated matrix YAML for verification
        cat jobs.yml
        
        # Join the array elements with a comma delimiter    
        CHANGED_FOLDERS=$(IFS=","; echo "${paths_without_filenames[*]}")
        echo "Content of CHANGED_FOLDERS"
        echo $CHANGED_FOLDERS
    
        echo "set output variable"
        echo "##vso[task.setvariable variable=EXAMPLE_FOLDERS;isOutput=true]$CHANGED_FOLDERS"

        git checkout -b pr_examples/$( system.pullRequest.sourceCommitId )
        git commit -am "Integration jobs"
        git push origin
      displayName: Getting the example folders
      name: changeset


